export const taiwan = {
  Taipei: {
    Taipei: [
      "Beitou",
      `Da'an`,
      "Datong",
      "Nangang",
      "Neihu",
      "Shilin",
      "Songshan",
      "Wanhua",
      "Wenshen",
      "Xinyi",
      "Zhongshan",
      "Zhongzheng",
    ],
    "New Taipei": [
      "Banqiao",
      `Xinzhuang`,
      "Zhonghe",
      "Yonghe",
      "Tucheng",
      "Shulin",
      "Sanxia",
      "Yingge",
      "Sanchong",
      "Luzhou",
      "Wugu",
      "Taishan",
      "Linkou",
      "Bali",
      "Tamsui",
      "Sanzhi",
      "Shimen",
      "Jinshan",
      "Wanli",
      "Xizhi",
      "Ruifang",
      "Gongliao",
      "Pingxi",
      "Shuangxi",
      "Xindian",
      "Shenkeng",
      "Shiding",
      "Pinglin",
      "Wulai",
    ],
    Taoyuan: [
      "Taoyuan",
      `Zhongli`,
      "Daxi",
      "Yangmei",
      "Luzhu",
      "Dayuan",
      "Guishan",
      "Bade",
      "Longtan",
      "Pingzhen",
      "Xinwu",
      "Guanyin",
      "Fuxing",
    ],
  },
  Taichung: {
    Taichung: [
      "Beitun",
      "Central",
      "Daan",
      "Dadu",
      "Dajia",
      "Dali",
      "Daya",
      "Dongshi",
      "Fengyuan",
      "Heping",
      "Houli",
      "Longjing",
      "Nantun",
      "Qingshui",
      "Shalu",
      "Shengang",
      "Taiping",
      "Tanzi",
      "Waipu",
      "Wufeng",
      "Wuqi",
      "Wuri",
      "Xinshe",
      "Xitun",
    ],
  },
  Kaoshiung: {
    Kaoshiung: [
      "Yancheng",
      "Gushan",
      "Zuoying",
      "Nanzih",
      "Sanmin",
      "Sinsing",
      "Cianjin",
      "Lingya",
      "Cianjhen",
      "Cijin",
      "Siaogang",
    ],
    Fengshan: [
      "Fengshan",
      "Linyuan",
      "Daliao",
      "Dashu",
      "Dashe",
      "Renwu",
      "Niaosong",
    ],
    Gangshan: [
      "Gangshan",
      "Ciaotou",
      "Yanchao",
      "Tianliao",
      "Alian",
      "Lujhu",
      "Hunei",
      "Cieding",
      "Yongan",
      "Mituo",
      "Zihguan",
    ],
    Cishan: ["Cishan", "Meinong", "Liouguei", "Jiansian", "Shanlin", "Neimen"],
  },
  Tainan: {
    Inner: ["West Central", "East", "South", "North", "Anping", "Annan"],
    "River South": [
      "Yongkang",
      "Gueiren",
      "Sinhua",
      "Zuojhen",
      "Yujing",
      "Nansi",
      "Nanhua",
      "Rende",
      "Guanmiao",
      "Longci",
      "Shanhua",
      "Shanshang",
    ],
  },
};

export const japan = {
  Tokyo: {
    Tokyo: [
      "Adachi",
      "Arakawa",
      "Bunkyo",
      "Chiyoda",
      "Chūō",
      "Edogawa",
      "Itabashi",
      "Katsushika",
      "Kita",
      "Kōtō",
      "Meguro",
      "Minato",
      "Nakano",
      "Nerima",
      "Ōta",
      "Setagaya",
      "Shibuya",
      "Shinagawa",
      "Shinjuku",
      "Suginami",
      "Sumida",
      "Taitō",
      "Toshima",
    ],
  },
};

const locationSettings = taiwan.Taichung;
export const mainDistricts = Object.keys(locationSettings);
export const subDistricts = Object.values(locationSettings);
